---
title: "Shiny App Example"
author: "Daniel Kuhman"
date: "May 29, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(shiny)
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Load and tidy data -->
```{r echo=FALSE, warning=FALSE}
mydata_path <- file.choose(new = FALSE)
mydata <- read.csv(mydata_path)
rm(mydata_path)

#Tidy data using normal tidyverse functions
mydata <- mydata %>% 
  select(Season, Player, Age, Tm, Pos, GP, G, A, PIM)
mydata$Season<-as.factor(mydata$Season)
mydata$Player<-as.factor(mydata$Player)
mydata$Age<-as.numeric(mydata$Age)
mydata$Tm<-as.factor(mydata$Tm)
mydata$GP<-as.numeric(mydata$GP)
mydata$G<-as.numeric(as.character(mydata$G))
mydata$A<-as.numeric(mydata$A)
mydata$PIM<-as.numeric(mydata$PIM)

mydata$GP[is.na(mydata$GP)]<-0
mydata$G[is.na(mydata$G)]<-0
mydata$A[is.na(mydata$A)]<-0
```

# **Interactive Exploration of NHL Data**

##Team Data
```{r select-input, echo=FALSE, warning=FALSE}
#Create panel for team and season
inputPanel(
  selectInput("Team", label = "Team:",
              choices = unique(mydata$Tm)
              ),
  renderUI({selectInput("Year", label = "Season:",
                      choices = unique(mydata$Season[mydata$Tm==input$Team]))
    }
  )
)

#Plot based on input
renderPlot({
  plot_data<- mydata %>% 
  filter(Tm == input$Team & Season == input$Year)
  
  ggplot(plot_data, aes(x=reorder(Player, G), y = G))+
    geom_point(aes(color=Player), size = 6)+
    geom_segment(aes(x=Player, xend=Player, y=0, yend=G,color=Player))+
    coord_flip()+
    xlab('Plyaer')+
    ylab('Goals Scored')+
    theme_classic()+
    theme(
      legend.position = 'none',
      axis.title.x = element_text(size=20, face='bold',
                                   margin=margin(t=25,r=0,b=0,l=0)),
      axis.title.y = element_text(size=20, face='bold',
                                   margin=margin(t=0,r=25,b=0,l=0)),
      axis.text = element_text(size=12)
    )
  }
)  
```

##Individual Player Data
```{r echo=FALSE}
renderUI({
 inputPanel(selectInput("Player", label="Player:",
                        choices=unique(mydata$Player[mydata$Tm==input$Team &
                                                   mydata$Season==input$Year]))
            )
})

renderPlot({
  player_plot_data<-mydata %>% 
    filter(Player == input$Player)
  
  ggplot(player_plot_data, aes(x=Season, y=G))+
    geom_point(size=6, color='#000066')+
    geom_line(aes(group=Player), size=2, color='#000066')+
    xlab('Season')+
    ylab('Goals Scored')+
    theme_classic()+
    theme(
      legend.position = 'none',
      axis.title.x = element_text(size=20, face='bold',
                                   margin=margin(t=25,r=0,b=0,l=0)),
      axis.title.y = element_text(size=20, face='bold',
                                   margin=margin(t=0,r=25,b=0,l=0)),
      axis.text = element_text(size=12)
    )
})

```





